spring:
  application:
    name: guli-edu
  datasource:
    url: jdbc:mysql://192.168.1.170:3306/guli_edu?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#    name:
server:
  port: 8110
